covariance:
    k: 0.1
    k_r: 0.5
    k_phi: 0.5
    
topic:
    encoder_wr: /wr
    encoder_wl: /wl
    pose_topic: /robot_posewithcovariance

odom:
    kl: 0.05
    kr: 0.05
    b: 0.09

file_path:
    goals_path_: "/home/zzx/Puzzlebot/src/multi_points_tracking/Goals2.txt"

controller:
    k_d: 0.1
    k_theta: 0.5
    threshold: 0.2

